name: elevar
description: A mobile app that uses the ESRGAN model to upscale images

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
#    git: https://github.com/ThangVuNguyenViet/tflite_flutter_plugin.git
#  tflite:
#    git: https://github.com/anohene1/flutter_tflite.git
  image_picker: ^0.8.4+11
  path_provider: ^2.0.9
  image: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/